# Generated by Django 2.2.7 on 2019-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
