# Generated by Django 2.2.7 on 2019-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postfile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
