# Generated by Django 2.2.7 on 2019-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191209_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='type',
            field=models.CharField(default='txt', max_length=100),
            preserve_default=False,
        ),
    ]
