# Generated by Django 2.2.7 on 2019-12-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191209_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post_images'),
        ),
    ]
