# Generated by Django 2.2.7 on 2019-12-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191210_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='post.Hashtag'),
        ),
    ]
