# Generated by Django 3.0.1 on 2019-12-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legalact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('is_yearly_plan', models.NullBooleanField(default=True)),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author_name', models.CharField(max_length=50)),
                ('authorized_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author_id', models.IntegerField(blank=True)),
                ('is_draft', models.NullBooleanField(default=True)),
                ('is_authorized', models.NullBooleanField(default=False)),
                ('is_deleted', models.NullBooleanField(default=False)),
                ('authorized_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legalacts', models.ManyToManyField(blank=True, related_name='legalacts', to='plan.Legalact')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('months', models.CharField(blank=True, max_length=200)),
                ('coherence', models.TextField(blank=True)),
                ('fund', models.TextField(blank=True)),
                ('baselevel', models.TextField(blank=True)),
                ('criteria', models.TextField(blank=True)),
                ('season1', models.TextField(blank=True)),
                ('season2', models.TextField(blank=True)),
                ('season3', models.TextField(blank=True)),
                ('season4', models.TextField(blank=True)),
                ('outcomename', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=-1)),
                ('text', models.TextField(blank=True)),
                ('months', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_action', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.PlanAction')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('measurement', models.TextField(blank=True)),
                ('base', models.TextField(blank=True)),
                ('halfyear', models.TextField(blank=True)),
                ('endofyear', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_goal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.PlanGoal')),
            ],
        ),
        migrations.AddField(
            model_name='planaction',
            name='plan_goal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.PlanGoal'),
        ),
    ]
