# Generated by Django 3.0.1 on 2019-12-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaction',
            name='plan_goal',
        ),
    ]
