# Generated by Django 3.0.1 on 2019-12-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_planaction_plan_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaction',
            name='plan_goal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.PlanGoal'),
        ),
    ]
