# Generated by Django 3.0.1 on 2020-01-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200102_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
