# Generated by Django 3.0.1 on 2020-01-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200102_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloptionvote',
            name='poll_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.PollOption'),
        ),
    ]
