# Generated by Django 3.0.1 on 2020-01-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200103_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_deleted',
            field=models.NullBooleanField(default=False),
        ),
    ]
