# Generated by Django 3.0.1 on 2020-01-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200103_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='can_add_options',
            field=models.NullBooleanField(default=False),
        ),
    ]
