# Generated by Django 3.0.1 on 2020-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_poll_can_add_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='can_check_multiple_option',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='can_add_options',
            field=models.NullBooleanField(default=True),
        ),
    ]
