# Generated by Django 3.0.1 on 2020-01-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200106_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloptionvote',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
