# Generated by Django 3.0.1 on 2020-01-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_polloptionvote_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polloption',
            name='user_name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
